// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZtE3zEXSROfHRUEMkhBk_s8m6CTr-kKA',
    appId: '1:3235098823:web:4afb95cb4e8b08c04ccee2',
    messagingSenderId: '3235098823',
    projectId: 'projectflutter-15fe4',
    authDomain: 'projectflutter-15fe4.firebaseapp.com',
    storageBucket: 'projectflutter-15fe4.appspot.com',
    measurementId: 'G-6R66M3S0NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6iTMtBL7YHOVNem8bYMnPfuMY1rfW0Q',
    appId: '1:3235098823:android:e8b6157c7c7f706c4ccee2',
    messagingSenderId: '3235098823',
    projectId: 'projectflutter-15fe4',
    storageBucket: 'projectflutter-15fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDIom6LPxUeotwZW0rtLW5a9jKx0nzx4',
    appId: '1:3235098823:ios:6590713e03be150e4ccee2',
    messagingSenderId: '3235098823',
    projectId: 'projectflutter-15fe4',
    storageBucket: 'projectflutter-15fe4.appspot.com',
    iosBundleId: 'com.example.projectFlutter',
  );
}
